# 1. 자연어의 특성
* 자연어를 기계가 처리하도록 하기 위해서는 먼저 자연어를 기계가 이해할 수 있는 언어로 바꾸는 방법을 알아야 함
* 토큰화 작업의 결과인 단어 사전을 기계가 이해할 수 있는 언어로 표현하는 과정이고 단어 사전 내 단어 하나를 어떻게 표현할까의 문제로 볼 수 있음

### 1-1. 단어의 유사성과 모호성
* 대부분의 언어에서 단어의 의미는 유사성과 모호성을 가지고 있는데 단어는 겉으로 보이는 형태인 표제어안에 여러가지 의미를 담고 있음
* 대부분 사람은 주변 정보에 따라 숨겨진 의미를 파악하고 이해할 수 있으나 기계는 학습의 부재 또는 잘못된 데이터로 의미를 파악하지 못하는 경우가 있음
* 한 가지 형태의 단어에 여러 의미가 포함되어 생기는 중의성 문제는 자연어 처리에서 매우 중요
    - 동형어와 다의어
        - 동형어: 형태는 같으나 뜻이 서로 다른 단어(배)
        - 다의어: 하나의 형태가 여러 의미를 지니면서도 그 의미들이 서로 관련이 있는 단어(먹다)
    - 동의어
        - 서로 다른 형태의 단어들이 동일한 의미를 가지는 단어
    - 상의어와 하위어
        - 상의어: 상위 개념을 가리키는 단어
        - 하위어: 하위 개념을 표현하는 단어

### 1-2. 언어의 모호성 해소
* 동형어나 다의어처럼 여러 의미를 가지는 단어들이 하나의 형태로 공유, 동의어처럼 하나의 형태를 가지는 단어들이 서로 같은 의미를 공유
* 단어 중의성 해소(WSD) 알고리즘 방법을 통해 단어의 의미를 명확히 함
    - 지식 기반 단어 중의성 해소
        * 컴퓨터가 읽을 수 있는 사전이나 시소러스(어휘집) 등을 바탕으로 단어의 의미를 추론하는 접근 방식
        * 사람이 직접 선별해서 데이터를 넣으므로 노이즈가 적음
        * 영어 자연어처리 분야에서 가장 유명한 WordNet이 있음
        * 관계 구축에 많은 리소스가 필요함
        * 시의성을 반영하지 못함
        * 데이터 편향이 생길 수 있음
    - 지도 학습 기반 단어 중의성 해소
        * 지도 학습은 데이터에 정답이 있다는 의미로, 각종 기계 학습 알고리즘을 통해 단어 의미를 분류해내는 방법
        * WSD라고 하면 보통 단어의 세부 의미가 부착된 코퍼스를 학습 데이터로 사용하여 학습에 쓰이지 않았던 새로운 문장에서 단어 의미를 판별해내는 경우
        * 좋은 성능을 위해서는 질 높은 레이블을 가진 크기가 큰 데이터가 필요함
        * 데이터가 충분할 경우 일반화된 환경에서도 괜찮은 성능을 낼 수 있음
    - 비지도 학습 기반 단어 중의성 해소
        * 비지도 학습 WSD는 단어 의미 추론 작업인 WSI를 가리키는 경우가 많음
        * 문장에 등장하는 각 단어의 의미를 사전적인 의미에 연결하지 않고, 세부 의미가 같은 맥락을 군집화하는 데에 초점을 맞춤
        * 대규모 자연어 코퍼스로부터 추가 작업 없이 자동적으로 학습을 수행할 수 있어서 활용 가능성이 높음
        * 사람이 직접 제작한 학습 데이터를 사용하지 않기 때문에 성능을 내기 어려움

# 2. 임베팅 구축 방법

### 2-1. 임베딩이란
* 자연어처리 작업에서 특징 추출을 통해 자연어를 수치화하는 과정이 필요하고, 이런 벡터화의 과정이자 결과
* 토큰화 작업의 목표는 사실상 임베딩을 만들기 위한 단어 사전을 구축하는 것

### 2-2. 임베딩의 역할
* 자연어의 의미적인 정보 함축
    * 자연어의 중요한 특징들을 추출하여 벡터로 압축하는 과정
    * 임베딩으로 표현된 문장은 실제 자연어의 주요 정보들을 포함하고 있음
    * 벡터인 만큼 사칙 연산이 가능하여 단어 벡터 간 덧셈/뺄셈을 통해 단어들 사이의 의미적 문법적 관계를 도출
    * 임베딩의 품질을 평가하기 위해 사용되는 단어 유추 평가 예시(https://word2vec.kr/search/)
* 자연어 간 유사도 계산
    * 자연어를 벡터로 표현하면, 코사인 유사도를 활용하여 두 벡터 간 유사도를 계산할 수 있음
    * 코사인 유사도는 -1이상 1이하의 값을 가지며 값이 1에 가까울수록 유사도가 높다고 판단함
* 전이 학습
    * 품질 좋은 임베딩을 사용할수록 목표로하는 자연어처리 작업의 학습 속도와 성능이 향상됨
    * 이미 만들어진 임베딩을 다른 작업을 학습하기 위한 입력값으로 쓰임 -> 전이 학습
    * 매번 새로운 것을 배울 때 scratch 부터 시작한다면 매 학습이 오래 걸림
    * 파인 튜닝: 학습하는데 임베딩을 초기화하여 사용하면 새로운 작업을 학습함에도 빠르게 학습할 수 있고 성능도 좋아짐

### 2-3. 임베딩을 만들 때 쓰는 통계적인 가설
* 문장을 구성하는데 어떤 단어가 얼마나 많이 쓰이는가?
* 문장에 어떤 단어가 같이 쓰이는가
* 단어가 어떤 순서로 등장하는가?

### 2-4. 단어 출현 빈도에 기반한 임베딩 구축 방법
* 원 핫 인코딩
    - 자연어를 0를 1로 구별하겠다는 인코딩 방법
    - 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고, 나머지 인덱스에는 0을 부여하는 벡터 표현 방식
    - 희소 문제(sparsity problem)
        * 예) 단어 사전의 크기가 10,000이라면, 총 10,000개 중 현재 단어를 표현하는 1개의 차원만 1이고, 나머지 9,999개의 차원은 0으로 표현
        * 대부분의 값들의 0인 행렬을 희소행렬이라 하는데, 단어가 늘어날수록 행렬의 크기는 계속 증가하나 증가하는 크기에 비해 표현의 효율성을 떨어짐
    - 단어의 유사도를 표현하지 못함
* Bag of words
    - 단어들의 순서는 전혀 고려하지 않고, 단어들의 출현빈도에 집중하는 자연어 코퍼스의 데이터 수치화 방법
    - 각 단어에 고유한 정수 인덱스를 부여하여 단어 집합을 생성하고, 각 인덱스의 위치에 단어 토큰의 등장 횟수를 기록한 벡터를 만듦
    - 단어 단위의 압축 방식이기 때문에 희소 문제와 단어 순서를 반영하지 못함
* TF-IDF
    - 단어의 빈도와 역문서 빈도를 사용하여 문서-단어 행렬 내 각 단어들의 중요한 정도를 가중치로 주는 표현 방법
    - 문서의 유사도를 구하는 작업, 검색 시스템에서 검색 결과의 중요도를 정하는 작업, 문서 내에서 특정 단어의 중요도를 구하는 작업 등에서 효과적으로 쓰일 수 있음
    - 단어의 중요도를 고려해도 여전히 단어의 빈도로 판단하는 표현 방식이기 때문에 맥락적 유사도를 반영하지 못함
    - 단어 사전의 규모 자체를 축소하는 방법이 아니기 때문에 단어 사전의 규모가 크다면 높은 계산 복잡도를 요구하는 표현 방식(희소 문제)
    
$$idf(d, t)= \log{}(\frac{n}{1+df(t)})$$

### 2-5. 분포 가설과 언어 모델
* 비슷한 위치(문맥) 내에서 등장하는 단어들은 비슷한 의미를 가진다는 가설
* 분포 가설은 목표 단어의 단어들, 즉 window 크기에 따라 정의되는 문맥의 의미를 이용해 단어를 벡터로 표현하는 것이 목표
* 분포 가설이라는 가정 하에 만들어진 표현 방법을 분산 표현이라고 함
* PMI(Pointwise Mutual Information)
    * 분포 가설의 대표적인 통계량은 PMI이며, 두 확률변수 사이의 상관성을 계량화하는 단위
    <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDymO_xD-V_OPxd28vuMt63YWiUrx1XT3QhQ&usqp=CAU'>
    * 확률변수가 완전히 독립인 경우에 값이 0이 되며, 독립이라는 말은 단어 x가 나타나는 것이 단어 y가 등장할 확률에 전혀 영향을 주지 않으며 반대로 단어 y의 등장이 단어 x에 영향을 주지 않는 것을 의미함
    * 단어 x가 등장할 때 문맥 내에 단어 y와 같이 자주 등장한다면 PMI값이 커짐
    * 분포 가설을 활용하는 대표적인 모델은 2013년 google의 [Efficient Estimation of Word Representations in Vector Space](https://arxiv.org/abs/1301.3781) 논문에서 발표된 Word2Vec이라는 단어 임베딩 기법


### 2-6. 단어가 어떤 순서로 쓰이는가
* 통계 기반 언어 모델
    - 언어 모델: 일련의 단어 토큰에 확률을 할당하는 모델
    - 단어의 등장 순서를 중요하게 고려하지 않았던 이전 가설들과 다르게, 언어 모델은 단어 시퀀스 정보를 명시적으로 학습함
    - 단어가 n개 주어졌을 때 언어 모델은 n개의 단어가 동시에 나타날 확률을 반환
    - 문장은 어순을 고려하여 여러 단어로 이루어진 단어 시퀀스라고도 부르며, n개의 단어로 구성된 단어 시퀀스를 확률적으로 표현
* 딥러닝 기반 언어 모델
    - 통계 기반 언어 모델에서는 여전히 등장 빈도라는 통계량을 활용하여 확률을 추산했지만, 딥러닝 기반 언어 모델들이 등장하면서 딥러닝 모델들이 입력과 출력 사이의 관계를 유연하게 정의할 수 있게 되고 그 자체로 확률 모델로 동작할 수 있음
        * MLM(Masked Language Modeling)
            - 문장 중간에 마스크릴 씌워서 해당 마스크에 어떤 단어가 올지 예측하는 과정에서 학습을 진행문장 전체를 다 보고 중간에 있는 단어를 예측하기 때문에 양방향 학습이 가능
            - 대표적으로 BERT 모델이 있음
        * Next Token Prediction
            - 주어진 단어 시퀀스를 가지고 다음 단어로 어떤 단어가 올지 예측하는 과정에서 학습
            - 단어를 순차적으로 입력 받은 뒤, 다음 단어를 맞춰야하기 때문에 일방향 학습을 함
            - 대표적으로 GPT, ELMo등


# 3. 텍스트 유사도
* 두 개의 자연어 텍스트가 얼마나 유사한지를 나타내는 방법
* 유사도를 정의하거나 판단하는 척도가 주관적이기 때문에, 이를 최대한 정량화하는 방법을 찾는 것이 중요함
* 자연어처리 분야에서 자주 사용되는 유사도 측정 방법
    - 유클리디안 거리 기반 유사도
    - 맨하탄 거리 기반 유사도
    - 코사인 유사도
    - 자카드 유사도
    - 문자열 간 유사도

### 3-1. 유클리디안 거리 기반 유사도
* 두 점 사이의 거리를 측정하는 유클리디안 거리를 사용하여 문서의 유사도를 구하는 방법으로 거리가 가까울수록 유사도가 높다고 판단함
* 자카드 유사도나 코사인 유사도만큼 유용하게 사용되는 방법은 아니나, 자연어처리 분야뿐만 아니라 다른 분야에서도 범용적으로 사용되는 거리 측정 기법

### 3-2. 맨하탄 거리 기반 유사도
* 맨하탄 거리를 사용하여 문서의 유사도를 구하는 방법
* 유클리드 거리와 유사하나, 각 차원의 차를 제곱해서 사용하는 대신 절대값을 바로 합산함
* 항상 유클리드 거리보다 크거나 같음
* 다차원 공간 상에서 두 좌표 간 최단거리를 구하는 방법이 아니다 보니 특별한 상황이 아니면 잘 사용하지 않음

### 3-3. 코사인 유사도
* 코사인 유사도는 두 개의 벡터값에서 코사인 각도를 이용하여 구할 수 있는 두 벡터의 유사도를 의미
* 두 벡터의 방향이 완전히 동일한 경우에는 1의 값을 가지며, 90도의 각을 이루면 0, 180도로 반대의 방향을 가지면 -1의 값을 가짐
* -1이상 1이하의 값을 가지며 값이 1에 가까울수록 유사하는 것을 의미
* 두 벡터가 가리키는 방향이 얼마나 유사한가를 의미하기 때문에 자연어 내 유사도 계산에 더 적합함

### 3-4. 자카드 유사도
* 두 문장을 각각 단어의 집합으로 만든 뒤 두 집합을 통해 유사도를 측정하는 방식
* 수치화된 벡터 없이 단어 집합 만으로 계산할 수 있음
* 두 집합의 교집한인 공통된 단어의 개수를 두 집합의 합집합, 전체 단어의 개수로 나누는 것
* 전체 합집합 중 공통의 단어의 개수에 따라 0과 1사이의 값을 가지며, 1에 가까울수록 유사도가 높음

# 4. 유사도 측정 실습

* sen_1, sen_2 : 의미가 유사한 문장 간 유사도 계산(조사 생략)
* sen_1, sen_3 : 의미가 유사한 문장 간 유사도 계산(순서 변경)
* sen_2, sen_4 : 문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산
* sen_1, sen_5 : 의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산
* sen_1, sen_6 : 의미가 서로 다른 문장 간 유사도 계산

In [2]:
sen_1 = '오늘 점심에 배가 너무 고파서 밥을 너무 많이 먹었다.'
sen_2 = '오늘 점심에 배가 고파서 밥을 많이 먹었다.'
sen_3 = '오늘 배가 너무 고파서 점심에 밥을 너무 많이 먹었다.'
sen_4 = '오늘 점심에 배가 고파서 비행기를 많이 먹었다.'
sen_5 = '어제 저녁에 밥을 너무 많이 먹었더니 배가 부르다.'
sen_6 = '이따가 오후 7시에 출발하는 비행기가 3시간 연착 되었다고 하네요.'

In [3]:
training_documents = [sen_1, sen_2, sen_3, sen_4, sen_5, sen_6]

In [4]:
!pip install newspaper3k

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.1/81.1 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 7.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 65.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for tinysegmenter: filename=tinysegmenter-0.3-py3-none-any.whl size=13541 sha256=6afcfcb018852c95372ad64f8bdd6ac29540e538b060fea24ff21692587cb3c4
  Stored in directory: /root/.cache/pip/wheels/c8/d6/6c/384f58df48c00b9a31d638005143b5b3ac62c3d25fb1447f23
  Created wheel for feedfinder2: filename=feedfinder2-0.0.4-py3-none-any.whl size=3341 sha256=8d2a83757c610cd612d37202045118506d2dc56bc6095a143b1208d437be57dd
  Stored in directory: /root/.cache/pip/wheels/97/02/e7/a1ff1760e12bdbaab0ac824fae5c1bc9

In [5]:
from newspaper import Article

In [6]:
URL = 'https://v.daum.net/v/20230628094638774'
article = Article(URL, language='ko')

In [7]:
article.download()
article.parse()

news_title = article.title
news_context = article.text

print('title: ', news_title)
print('context: ', news_context)

title:  당정 "'예비군 훈련 대학생' 학습권 보장…2학기부터 시행"
context:  당정, 예비군 학생 학습권 보호 협의 (서울=연합뉴스) 한상균 기자 = 28일 국회에서 열린 예비군 훈련 학생 학습권 보호 당정협의회에서 국민의힘 박대출 정책위의장이 발언하고 있다. 오른쪽은 이주호 부총리 겸 교육부 장관, 이종섭 국방부 장관. 2023.6.28 xyz@yna.co.kr

(서울=연합뉴스) 최평천 곽민서 기자 = 국민의힘과 정부는 28일 예비군 훈련으로 대학 수업에 결석했을 때 불이익을 주지 못하도록 시행령을 개정하기로 했다.

이주호 부총리 겸 교육부 장관은 이날 국회에서 '예비군 훈련 참여 학생에 대한 학습권 보호' 당정 협의회에 참석해 "고등교육법 시행령에 학습권 보장 내용을 신설하고, 국방부와 협조해 불이익 사례가 발생하지 않는지 현장을 면밀히 살피겠다"고 밝혔다.

이 부총리는 "청년들이 국가를 위해 헌신한 시간은 존중돼야지 불이익으로 돌아가서는 안 될 것"이라며 "대학 학칙에 해당 내용을 규정하도록 하겠다"고 덧붙였다.

국민의힘 박대출 정책위의장은 모두발언에서 "이날 당정 협의회는 예비군 참여 학생의 학습권을 보장하기 위해 열렸다"며 "국가가 불러서 지정된 날짜에 예비군 훈련을 받으러 갔더니 대학 수업에 빠졌다면서 불이익을 받는다면 학생 입장에서 억울하게 느낄 수밖에 없다"고 지적했다.

이어 "예비군 훈련에 따른 피해가 없도록 하고 학습권을 보장하는 방안도 마련하겠다"며 "2학기 시작 전에 (관련 대책이) 시행될 수 있도록, 청년들이 더는 억울하거나 허탈감을 느끼지 않도록 할 것"이라고 말했다.

국회 교육위원회 여당 간사인 이태규 의원은 일부 대학에서 예비군 훈련을 이유로 불이익을 준 점을 거론, "병역 의무를 다한 학생에 대한 올바른 대우와 태도가 아님은 분명하다"고 비판했다.

또 "재발방지책을 강구해야 하겠지만 더 중요한 것은 병역 의무를 성실하게 마친 청년들을 기억하고 존중하는 사회를 만드는 것이라고 생각한다"고 밝혔다.

이종섭

In [8]:
news_context = article.text.split('\n')

In [9]:
for text in news_context:
    print(text)

당정, 예비군 학생 학습권 보호 협의 (서울=연합뉴스) 한상균 기자 = 28일 국회에서 열린 예비군 훈련 학생 학습권 보호 당정협의회에서 국민의힘 박대출 정책위의장이 발언하고 있다. 오른쪽은 이주호 부총리 겸 교육부 장관, 이종섭 국방부 장관. 2023.6.28 xyz@yna.co.kr

(서울=연합뉴스) 최평천 곽민서 기자 = 국민의힘과 정부는 28일 예비군 훈련으로 대학 수업에 결석했을 때 불이익을 주지 못하도록 시행령을 개정하기로 했다.

이주호 부총리 겸 교육부 장관은 이날 국회에서 '예비군 훈련 참여 학생에 대한 학습권 보호' 당정 협의회에 참석해 "고등교육법 시행령에 학습권 보장 내용을 신설하고, 국방부와 협조해 불이익 사례가 발생하지 않는지 현장을 면밀히 살피겠다"고 밝혔다.

이 부총리는 "청년들이 국가를 위해 헌신한 시간은 존중돼야지 불이익으로 돌아가서는 안 될 것"이라며 "대학 학칙에 해당 내용을 규정하도록 하겠다"고 덧붙였다.

국민의힘 박대출 정책위의장은 모두발언에서 "이날 당정 협의회는 예비군 참여 학생의 학습권을 보장하기 위해 열렸다"며 "국가가 불러서 지정된 날짜에 예비군 훈련을 받으러 갔더니 대학 수업에 빠졌다면서 불이익을 받는다면 학생 입장에서 억울하게 느낄 수밖에 없다"고 지적했다.

이어 "예비군 훈련에 따른 피해가 없도록 하고 학습권을 보장하는 방안도 마련하겠다"며 "2학기 시작 전에 (관련 대책이) 시행될 수 있도록, 청년들이 더는 억울하거나 허탈감을 느끼지 않도록 할 것"이라고 말했다.

국회 교육위원회 여당 간사인 이태규 의원은 일부 대학에서 예비군 훈련을 이유로 불이익을 준 점을 거론, "병역 의무를 다한 학생에 대한 올바른 대우와 태도가 아님은 분명하다"고 비판했다.

또 "재발방지책을 강구해야 하겠지만 더 중요한 것은 병역 의무를 성실하게 마친 청년들을 기억하고 존중하는 사회를 만드는 것이라고 생각한다"고 밝혔다.

이종섭 국방부 장관은 "학생 예비군들이 안심하고 훈련에 전념할 수 있는 여건을 마련하기 위해 국회,

In [10]:
!pip install kss

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 47.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for kss: filename=kss-4.5.3-py3-none-any.whl size=54258 sha256=431bf9ac9c7634bbf1aa8757f77c9c2c9c2e7e9a0ac4753f0c507ebae3b10a83
  Stored in directory: /root/.cache/pip/wheels/d8/9e/a3/5b09e3f14722fa0d77f47fe840668d426760023bdd11b0fbd9
  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646666 sha256=e8a01d5c3e0860c4379b75777ec3508cf28519aac40e14a123c517b3fa4cef3e
  Stored in directory: /root/.cache/pip/wheels/5c/6f/b4/ab61b8863d7d8b1409def8ae31adcaa089fa91b8d022ec309d
Successfully built kss pecab


In [11]:
import kss

In [12]:
def sentence_seperator(processed_context):
    splited_context = []

    for text in processed_context:
        text = text.strip()
        if text:
            splited_text = kss.split_sentences(text)
            splited_context.extend(splited_text)

    return splited_context

In [13]:
splited_context = sentence_seperator(news_context)

for text in enumerate(splited_context):
    print(text)

For your information, Kss also supports mecab backend.
We recommend you to install mecab or konlpy.tag.Mecab for faster execution of Kss.
Please refer to following web sites for details:
- mecab: https://github.com/hyunwoongko/python-mecab-kor
- konlpy.tag.Mecab: https://konlpy.org/en/latest/api/konlpy.tag/#mecab-class



(0, '당정, 예비군 학생 학습권 보호 협의 (서울=연합뉴스) 한상균 기자 = 28일 국회에서 열린 예비군 훈련 학생 학습권 보호 당정협의회에서 국민의힘 박대출 정책위의장이 발언하고 있다.')
(1, '오른쪽은 이주호 부총리 겸 교육부 장관, 이종섭 국방부 장관.')
(2, '2023.6.28 xyz@yna.co.kr')
(3, '(서울=연합뉴스) 최평천 곽민서 기자 = 국민의힘과 정부는 28일 예비군 훈련으로 대학 수업에 결석했을 때 불이익을 주지 못하도록 시행령을 개정하기로 했다.')
(4, '이주호 부총리 겸 교육부 장관은 이날 국회에서 \'예비군 훈련 참여 학생에 대한 학습권 보호\' 당정 협의회에 참석해 "고등교육법 시행령에 학습권 보장 내용을 신설하고, 국방부와 협조해 불이익 사례가 발생하지 않는지 현장을 면밀히 살피겠다"고 밝혔다.')
(5, '이 부총리는 "청년들이 국가를 위해 헌신한 시간은 존중돼야지 불이익으로 돌아가서는 안 될 것"이라며 "대학 학칙에 해당 내용을 규정하도록 하겠다"고 덧붙였다.')
(6, '국민의힘 박대출 정책위의장은 모두발언에서 "이날 당정 협의회는 예비군 참여 학생의 학습권을 보장하기 위해 열렸다"며 "국가가 불러서 지정된 날짜에 예비군 훈련을 받으러 갔더니 대학 수업에 빠졌다면서 불이익을 받는다면 학생 입장에서 억울하게 느낄 수밖에 없다"고 지적했다.')
(7, '이어 "예비군 훈련에 따른 피해가 없도록 하고 학습권을 보장하는 방안도 마련하겠다"며 "2학기 시작 전에 (관련 대책이) 시행될 수 있도록, 청년들이 더는 억울하거나 허탈감을 느끼지 않도록 할 것"이라고 말했다.')
(8, '국회 교육위원회 여당 간사인 이태규 의원은 일부 대학에서 예비군 훈련을 이유로 불이익을 준 점을 거론, "병역 의무를 다한 학생에 대한 올바른 대우와 태도가 아님은 분명하다"고 비판했다.')
(9, '또 "재발방지책을 강구해야 하겠지만 더 중요한 것은 병역 의무를 성실하게 마친 청년들을 기억하고 존중하는 사회를 만드는 것이라고 생각한다"

In [14]:
augmented_training_documents = training_documents + splited_context

In [15]:
for text in augmented_training_documents:
    print(text)

오늘 점심에 배가 너무 고파서 밥을 너무 많이 먹었다.
오늘 점심에 배가 고파서 밥을 많이 먹었다.
오늘 배가 너무 고파서 점심에 밥을 너무 많이 먹었다.
오늘 점심에 배가 고파서 비행기를 많이 먹었다.
어제 저녁에 밥을 너무 많이 먹었더니 배가 부르다.
이따가 오후 7시에 출발하는 비행기가 3시간 연착 되었다고 하네요.
당정, 예비군 학생 학습권 보호 협의 (서울=연합뉴스) 한상균 기자 = 28일 국회에서 열린 예비군 훈련 학생 학습권 보호 당정협의회에서 국민의힘 박대출 정책위의장이 발언하고 있다.
오른쪽은 이주호 부총리 겸 교육부 장관, 이종섭 국방부 장관.
2023.6.28 xyz@yna.co.kr
(서울=연합뉴스) 최평천 곽민서 기자 = 국민의힘과 정부는 28일 예비군 훈련으로 대학 수업에 결석했을 때 불이익을 주지 못하도록 시행령을 개정하기로 했다.
이주호 부총리 겸 교육부 장관은 이날 국회에서 '예비군 훈련 참여 학생에 대한 학습권 보호' 당정 협의회에 참석해 "고등교육법 시행령에 학습권 보장 내용을 신설하고, 국방부와 협조해 불이익 사례가 발생하지 않는지 현장을 면밀히 살피겠다"고 밝혔다.
이 부총리는 "청년들이 국가를 위해 헌신한 시간은 존중돼야지 불이익으로 돌아가서는 안 될 것"이라며 "대학 학칙에 해당 내용을 규정하도록 하겠다"고 덧붙였다.
국민의힘 박대출 정책위의장은 모두발언에서 "이날 당정 협의회는 예비군 참여 학생의 학습권을 보장하기 위해 열렸다"며 "국가가 불러서 지정된 날짜에 예비군 훈련을 받으러 갔더니 대학 수업에 빠졌다면서 불이익을 받는다면 학생 입장에서 억울하게 느낄 수밖에 없다"고 지적했다.
이어 "예비군 훈련에 따른 피해가 없도록 하고 학습권을 보장하는 방안도 마련하겠다"며 "2학기 시작 전에 (관련 대책이) 시행될 수 있도록, 청년들이 더는 억울하거나 허탈감을 느끼지 않도록 할 것"이라고 말했다.
국회 교육위원회 여당 간사인 이태규 의원은 일부 대학에서 예비군 훈련을 이유로 불이익을 준 점을 거론, "병역 의무를 다한 학생

In [16]:
# Bag of Words 기반 문서-단어 행렬을 활용한 문장 간 유사도 측정
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
bow_vectorizer = CountVectorizer()
bow_vectorizer.fit(augmented_training_documents)

CountVectorizer()

In [19]:
word_idxes = bow_vectorizer.vocabulary_

for key, idx in sorted(word_idxes.items()):
    print(f'{key}: {idx}')

2023: 0
28: 1
28일: 2
2학기: 3
3시간: 4
7시에: 5
co: 6
kr: 7
okjebo: 8
pc: 9
xyz: 10
yna: 11
간사인: 12
갔더니: 13
강구해야: 14
개정하기로: 15
거론: 16
것은: 17
것이라고: 18
결석했을: 19
고등교육법: 20
고파서: 21
곽민서: 22
관계부처: 23
관련: 24
교육부: 25
교육위원회: 26
국가가: 27
국가를: 28
국민의힘: 29
국민의힘과: 30
국방부: 31
국방부와: 32
국방위원회: 33
국방장관: 34
국회: 35
국회에서: 36
권익: 37
규정하도록: 38
기억하고: 39
기여할: 40
기자: 41
김병민: 42
날짜에: 43
내용을: 44
너무: 45
노력을: 46
느끼지: 47
느낄: 48
다한: 49
당에서: 50
당정: 51
당정협의회에서: 52
대우와: 53
대책이: 54
대학: 55
대학에서: 56
대한: 57
더는: 58
덧붙였다: 59
돌아가서는: 60
되었다고: 61
등이: 62
따른: 63
마련하겠다: 64
마련하기: 65
마친: 66
만드는: 67
많이: 68
말했다: 69
먹었다: 70
먹었더니: 71
면밀히: 72
모두발언에서: 73
못하도록: 74
박대출: 75
받는다면: 76
받으러: 77
발생하지: 78
발언하고: 79
밝혔다: 80
밥을: 81
방안도: 82
배가: 83
병역: 84
보장: 85
보장에: 86
보장하기: 87
보장하는: 88
보호: 89
부르다: 90
부총리: 91
부총리는: 92
부총리와: 93
분명하다: 94
불러서: 95
불이익: 96
불이익으로: 97
불이익을: 98
비판했다: 99
비행기가: 100
비행기를: 101
빠졌다면서: 102
사례가: 103
사회를: 104
살피겠다: 105
생각한다: 106
서울: 107
성실하게: 108
수밖에: 109
수업에: 110
시간은: 111
시작: 112
시행될: 113
시행령에: 114
시행령을: 115
신설하고: 116
신원식: 117
아님은: 118
안심하

In [20]:
import pandas as pd

In [23]:
result = []
vocab = list(word_idxes.keys())

for i in range(len(training_documents)):
    result.append([])
    d = training_documents[i]
    for j in range(len(vocab)):
        target = vocab[j]
        result[-1].append(d.count(target))

tf = pd.DataFrame(result, columns=vocab)
tf

오늘  점심에  배가  너무  고파서  밥을  많이  먹었다  비행기를  어제  ...  등이  참석했다  정부에서는  부총리와  \
0   1    1   1   2    1   1   1    1     0   0  ...   0     0      0     0   
1   1    1   1   0    1   1   1    1     0   0  ...   0     0      0     0   
2   1    1   1   2    1   1   1    1     0   0  ...   0     0      0     0   
3   1    1   1   0    1   0   1    1     1   0  ...   0     0      0     0   
4   0    0   1   1    0   1   1    0     0   1  ...   0     0      0     0   
5   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   

   국방장관  자리했다  pc  제보는  카톡  okjebo  
0     0     0   0    0   0       0  
1     0     0   0    0   0       0  
2     0     0   0    0   0       0  
3     0     0   0    0   0       0  
4     0     0   0    0   0       0  
5     0     0   0    0   0       0  

[6 rows x 220 columns]

In [24]:
result = []
vocab = list(word_idxes.keys())

for i in range(len(augmented_training_documents)):
    result.append([])
    d = augmented_training_documents[i]
    for j in range(len(vocab)):
        target = vocab[j]
        result[-1].append(d.count(target))

tf = pd.DataFrame(result, columns=vocab)
tf

오늘  점심에  배가  너무  고파서  밥을  많이  먹었다  비행기를  어제  ...  등이  참석했다  정부에서는  부총리와  \
0    1    1   1   2    1   1   1    1     0   0  ...   0     0      0     0   
1    1    1   1   0    1   1   1    1     0   0  ...   0     0      0     0   
2    1    1   1   2    1   1   1    1     0   0  ...   0     0      0     0   
3    1    1   1   0    1   0   1    1     1   0  ...   0     0      0     0   
4    0    0   1   1    0   1   1    0     0   1  ...   0     0      0     0   
5    0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
6    0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
7    0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
8    0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
9    0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
10   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
11   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
12   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
13   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
14   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
15   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
16   1    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
17   0    0   0   0    0   0   0    0     0   0  ...   1     1      0     0   
18   0    0   0   0    0   0   0    0     0   0  ...   1     0      1     1   
19   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   
20   0    0   0   0    0   0   0    0     0   0  ...   0     0      0     0   

    국방장관  자리했다  pc  제보는  카톡  okjebo  
0      0     0   0    0   0       0  
1      0     0   0    0   0       0  
2      0     0   0    0   0       0  
3      0     0   0    0   0       0  
4      0     0   0    0   0       0  
5      0     0   0    0   0       0  
6      0     0   0    0   0       0  
7      0     0   0    0   0       0  
8      0     0   0    0   0       0  
9      0     0   0    0   0       0  
10     0     0   0    0   0       0  
11     0     0   0    0   0       0  
12     0     0   0    0   0       0  
13     0     0   0    0   0       0  
14     0     0   0    0   0       0  
15     0     0   0    0   0       0  
16     0     0   0    0   0       0  
17     0     0   0    0   0       0  
18     1     1   0    0   0       0  
19     0     0   1    0   0       0  
20     0     0   0    1   1       1  

[21 rows x 220 columns]

In [27]:
# 유사도를 측정할 문장들을 문장-단어 행렬 기반 임베딩으로 변환
bow_vector_sen_1 = bow_vectorizer.transform([sen_1]).toarray()[0]
bow_vector_sen_2 = bow_vectorizer.transform([sen_2]).toarray()[0]
bow_vector_sen_3 = bow_vectorizer.transform([sen_3]).toarray()[0]
bow_vector_sen_4 = bow_vectorizer.transform([sen_4]).toarray()[0]
bow_vector_sen_5 = bow_vectorizer.transform([sen_5]).toarray()[0]
bow_vector_sen_6 = bow_vectorizer.transform([sen_6]).toarray()[0]

In [28]:
print(bow_vector_sen_1)
print(bow_vector_sen_2)
print(bow_vector_sen_3)
print(bow_vector_sen_4)
print(bow_vector_sen_5)
print(bow_vector_sen_6)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 

In [29]:
# 코사인 기반 유사도 계산을 위해 함수를 정의
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [30]:
def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))

* sen_1, sen_2 : 의미가 유사한 문장 간 유사도 계산(조사 생략)
* sen_1, sen_3 : 의미가 유사한 문장 간 유사도 계산(순서 변경)
* sen_2, sen_4 : 문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산
* sen_1, sen_5 : 의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산
* sen_1, sen_6 : 의미가 서로 다른 문장 간 유사도 계산

In [38]:
print(f'의미가 유사한 문장 간 유사도 계산(조사 생략): {cos_sim(bow_vector_sen_1, bow_vector_sen_2)}')
print(f'의미가 유사한 문장 간 유사도 계산(순서 변경): {cos_sim(bow_vector_sen_1, bow_vector_sen_3)}')
print(f'문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: {cos_sim(bow_vector_sen_2, bow_vector_sen_4)}')
print(f'의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: {cos_sim(bow_vector_sen_1, bow_vector_sen_5)}')
print(f'의미가 서로 다른 문장 간 유사도 계산: {cos_sim(bow_vector_sen_1, bow_vector_sen_6)}')

의미가 유사한 문장 간 유사도 계산(조사 생략): 0.7977240352174656
의미가 유사한 문장 간 유사도 계산(순서 변경): 1.0
문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: 0.857142857142857
의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: 0.5330017908890261
의미가 서로 다른 문장 간 유사도 계산: 0.0


In [39]:
# TF-IDF기반 문서-단어 행렬을 활용한 문장 간 유사도 측정
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidfv = TfidfVectorizer().fit(augmented_training_documents)

In [42]:
for key, idx in sorted(tfidfv.vocabulary_.items()):
    print(f'{key}: {idx}')

2023: 0
28: 1
28일: 2
2학기: 3
3시간: 4
7시에: 5
co: 6
kr: 7
okjebo: 8
pc: 9
xyz: 10
yna: 11
간사인: 12
갔더니: 13
강구해야: 14
개정하기로: 15
거론: 16
것은: 17
것이라고: 18
결석했을: 19
고등교육법: 20
고파서: 21
곽민서: 22
관계부처: 23
관련: 24
교육부: 25
교육위원회: 26
국가가: 27
국가를: 28
국민의힘: 29
국민의힘과: 30
국방부: 31
국방부와: 32
국방위원회: 33
국방장관: 34
국회: 35
국회에서: 36
권익: 37
규정하도록: 38
기억하고: 39
기여할: 40
기자: 41
김병민: 42
날짜에: 43
내용을: 44
너무: 45
노력을: 46
느끼지: 47
느낄: 48
다한: 49
당에서: 50
당정: 51
당정협의회에서: 52
대우와: 53
대책이: 54
대학: 55
대학에서: 56
대한: 57
더는: 58
덧붙였다: 59
돌아가서는: 60
되었다고: 61
등이: 62
따른: 63
마련하겠다: 64
마련하기: 65
마친: 66
만드는: 67
많이: 68
말했다: 69
먹었다: 70
먹었더니: 71
면밀히: 72
모두발언에서: 73
못하도록: 74
박대출: 75
받는다면: 76
받으러: 77
발생하지: 78
발언하고: 79
밝혔다: 80
밥을: 81
방안도: 82
배가: 83
병역: 84
보장: 85
보장에: 86
보장하기: 87
보장하는: 88
보호: 89
부르다: 90
부총리: 91
부총리는: 92
부총리와: 93
분명하다: 94
불러서: 95
불이익: 96
불이익으로: 97
불이익을: 98
비판했다: 99
비행기가: 100
비행기를: 101
빠졌다면서: 102
사례가: 103
사회를: 104
살피겠다: 105
생각한다: 106
서울: 107
성실하게: 108
수밖에: 109
수업에: 110
시간은: 111
시작: 112
시행될: 113
시행령에: 114
시행령을: 115
신설하고: 116
신원식: 117
아님은: 118
안심하

In [44]:
sk_tf_idf = tfidfv.transform(augmented_training_documents).toarray()
print(sk_tf_idf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [45]:
# TF-IDF 행렬에서 얻어지는 유사도의 값을 0 ~ 1로 스케일링하기 위해 L1 정규화를 진행
def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

In [47]:
fidf_vectorizer = TfidfVectorizer()
fidf_matrix_l1 = fidf_vectorizer.fit_transform(augmented_training_documents)
fidf_norm_l1 = l1_normalize(fidf_matrix_l1)
fidf_norm_l1

<21x220 sparse matrix of type '<class 'numpy.float64'>'
	with 303 stored elements in Compressed Sparse Row format>

In [48]:
tf_sen_1 = fidf_norm_l1[0:1]
tf_sen_2 = fidf_norm_l1[1:2]
tf_sen_3 = fidf_norm_l1[2:3]
tf_sen_4 = fidf_norm_l1[3:4]
tf_sen_5 = fidf_norm_l1[4:5]
tf_sen_6 = fidf_norm_l1[5:6]
tf_sen_1

<1x220 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [49]:
tf_sen_1.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00399858, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00871626, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.00370481, 0.        ,
        0.00399858, 0.        , 0.        , 0.  

In [50]:
# 유클리디안 거리 기반 유사도 측정
from sklearn.metrics.pairwise import euclidean_distances

In [51]:
euclidean_distances(tf_sen_1, tf_sen_2)

array([[0.00928653]])

In [52]:
def euclidean_distances_value(vec_1, vec_2):
    return round(euclidean_distances(vec_1, vec_2)[0][0], 3)

In [53]:
print(f'의미가 유사한 문장 간 유사도 계산(조사 생략): {euclidean_distances_value(tf_sen_1, tf_sen_2)}')
print(f'의미가 유사한 문장 간 유사도 계산(순서 변경): {euclidean_distances_value(tf_sen_1, tf_sen_3)}')
print(f'문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: {euclidean_distances_value(tf_sen_2, tf_sen_4)}')
print(f'의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: {euclidean_distances_value(tf_sen_1, tf_sen_5)}')
print(f'의미가 서로 다른 문장 간 유사도 계산: {euclidean_distances_value(tf_sen_1, tf_sen_6)}')

의미가 유사한 문장 간 유사도 계산(조사 생략): 0.009
의미가 유사한 문장 간 유사도 계산(순서 변경): 0.0
문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: 0.009
의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: 0.014
의미가 서로 다른 문장 간 유사도 계산: 0.019


In [54]:
from sklearn.metrics.pairwise import manhattan_distances, cosine_similarity

In [59]:
# 맨해튼 거리 기반 유사도 측정
def manhattan_distances_value(vec_1, vec_2):
    return round(manhattan_distances(vec_1, vec_2)[0][0], 3)

In [60]:
print(f'의미가 유사한 문장 간 유사도 계산(조사 생략): {manhattan_distances_value(tf_sen_1, tf_sen_2)}')
print(f'의미가 유사한 문장 간 유사도 계산(순서 변경): {manhattan_distances_value(tf_sen_1, tf_sen_3)}')
print(f'문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: {manhattan_distances_value(tf_sen_2, tf_sen_4)}')
print(f'의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: {manhattan_distances_value(tf_sen_1, tf_sen_5)}')
print(f'의미가 서로 다른 문장 간 유사도 계산: {manhattan_distances_value(tf_sen_1, tf_sen_6)}')

의미가 유사한 문장 간 유사도 계산(조사 생략): 0.017
의미가 유사한 문장 간 유사도 계산(순서 변경): 0.0
문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: 0.014
의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: 0.042
의미가 서로 다른 문장 간 유사도 계산: 0.076


In [61]:
# 코사인 유사도 측정
def cosine_similarity_value(vec_1, vec_2):
    return round(cosine_similarity(vec_1, vec_2)[0][0], 3)

In [62]:
print(f'의미가 유사한 문장 간 유사도 계산(조사 생략): {cosine_similarity_value(tf_sen_1, tf_sen_2)}')
print(f'의미가 유사한 문장 간 유사도 계산(순서 변경): {cosine_similarity_value(tf_sen_1, tf_sen_3)}')
print(f'문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: {cosine_similarity_value(tf_sen_2, tf_sen_4)}')
print(f'의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: {cosine_similarity_value(tf_sen_1, tf_sen_5)}')
print(f'의미가 서로 다른 문장 간 유사도 계산: {cosine_similarity_value(tf_sen_1, tf_sen_6)}')

의미가 유사한 문장 간 유사도 계산(조사 생략): 0.762
의미가 유사한 문장 간 유사도 계산(순서 변경): 1.0
문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: 0.797
의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: 0.448
의미가 서로 다른 문장 간 유사도 계산: 0.0


In [63]:
# 언어 모델을 활용한 문장 간 유사도 측정
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 43.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 18.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 82.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 56.4 MB/s eta 0:00:00


In [64]:
from transformers import AutoModel, AutoTokenizer, BertTokenizer

In [65]:
MODEL_NAME = 'bert-base-multilingual-cased'

model = AutoModel.from_pretrained(MODEL_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [67]:
bert_sen_1 = tokenizer(sen_1, return_tensors='pt')
bert_sen_2 = tokenizer(sen_2, return_tensors='pt')
bert_sen_3 = tokenizer(sen_3, return_tensors='pt')
bert_sen_4 = tokenizer(sen_4, return_tensors='pt')
bert_sen_5 = tokenizer(sen_5, return_tensors='pt')
bert_sen_6 = tokenizer(sen_6, return_tensors='pt')

In [69]:
sen_1_outputs = model(**bert_sen_1)
sen_1_pooler_output = sen_1_outputs.pooler_output

sen_2_outputs = model(**bert_sen_2)
sen_2_pooler_output = sen_2_outputs.pooler_output

sen_3_outputs = model(**bert_sen_3)
sen_3_pooler_output = sen_3_outputs.pooler_output

sen_4_outputs = model(**bert_sen_4)
sen_4_pooler_output = sen_4_outputs.pooler_output

sen_5_outputs = model(**bert_sen_5)
sen_5_pooler_output = sen_5_outputs.pooler_output

sen_6_outputs = model(**bert_sen_6)
sen_6_pooler_output = sen_6_outputs.pooler_output

In [70]:
from torch import nn

In [71]:
cos_sim = nn.CosineSimilarity(dim=1, eps=1e-6)

In [72]:
print(f'의미가 유사한 문장 간 유사도 계산(조사 생략): {cos_sim(sen_1_pooler_output, sen_2_pooler_output)}')
print(f'의미가 유사한 문장 간 유사도 계산(순서 변경): {cos_sim(sen_1_pooler_output, sen_3_pooler_output)}')
print(f'문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: {cos_sim(sen_2_pooler_output, sen_4_pooler_output)}')
print(f'의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: {cos_sim(sen_1_pooler_output, sen_5_pooler_output)}')
print(f'의미가 서로 다른 문장 간 유사도 계산: {cos_sim(sen_1_pooler_output, sen_6_pooler_output)}')

의미가 유사한 문장 간 유사도 계산(조사 생략): tensor([0.9901], grad_fn=<SumBackward1>)
의미가 유사한 문장 간 유사도 계산(순서 변경): tensor([0.9972], grad_fn=<SumBackward1>)
문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산: tensor([0.9916], grad_fn=<SumBackward1>)
의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산: tensor([0.9744], grad_fn=<SumBackward1>)
의미가 서로 다른 문장 간 유사도 계산: tensor([0.9533], grad_fn=<SumBackward1>)
